theme: jekyll-theme-minimal

title: Simon Pickstone
description: Freelance environmental journalist based in Heidelberg, Germany.
url: "https://simonpickstone.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
