theme: jekyll-theme-minimal
title: Simon Pickstone
url: "https://simonpickstone.github.io"
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image: /images/simon_pickstone.jpeg
